apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: profile
  namespace: {{ template "profile.namespace" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ template "profile.hostname" . }}
    http:
      paths:
      - backend:
          service:
            name: profile
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ template "profile.hostname" . }}
    secretName: rickydj-tls
