apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: profile
  name: profile
  namespace: {{ template "profile.namespace" . }}
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: profile
  type: ClusterIP
status:
  loadBalancer: {}
