apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      parameters:
        - name: deployment.tag
          value: $ARGOCD_APP_REVISION_SHORT
    path: chart
    repoURL: git@github.com:rickydjohn/profile.git
    targetRevision: HEAD
  syncPolicy:
    automated: {} 
    syncOptions:
    - CreateNamespace=true
