presubmits:
  rickydjohn/profile:
    - name: check-prow-config
      branches:
        - ^main$
      decorate: true
      decoration_config:
        ssh_key_secrets:
        - gh-ssh-key
      clone_uri: "git@github.com:rickydjohn/profile.git"
      skip_report: false
      run_if_changed: 'prow-config/.*'
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20231019-811baf28f3
            command:
              - /ko-app/checkconfig
            args:
            - --config-path=prow-config/config.yaml
            - --job-config-path=prow-config/jobs
            - --plugin-config=prow-config/plugins.yaml
