name: custom-build-pr

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: get build short ID
        run: echo "IMAGE_NAME=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: print build short ID
        run: echo ${{ GITHUB_CONTEXT }} ${{ env.IMAGE_NAME }} ${{ GITHUB_REF }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rickydjohn/profile:${{ env.IMAGE_NAME }}
