name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: print shell
        run: env

      - name: actual commit id
        uses: 2428392/gh-truncate-string-action@v1.2.0
        id: truncatedString
        with:
          stringToTruncate: ${GITHUB_SHA}
          maxLength: 7

      - name: print rev-parse out
        run: echo ${{ steps.truncatedString.outputs.string }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rickydjohn/profile:${{ steps.truncatedString.outputs.string }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rickydjohn/profile:latest
